name: Build Vue
on:
  push:
    branches:
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js '18.x'
      uses: actions/setup-node@v2
      with:
        node-version: "18.x"
        cache: "npm"
    - id: Build-Vue
      uses: SerhiiKa/VuePagesAction@1.0.4
      with:
        username: 'Mittelblut9'
        reponame: 'rock-n-paper'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
